# Mmap SDK vs traditional SDK comparison
# 
# This Compose spins up two Java severs -
# 1. A simple Java http server using a traditional OpenTelemetry SDK
# 2. A simple Java http server using a streamlined MMAP SDK.
#
# This runs cadvisor + k6 load testing on each server to demonstrate latency + performance characteristics.
#
# A machine-local (but separate container) collector reads the file
# and processes data into actual OTLP which is sent to an
# OpenTelemetry collector
x-otlp-mmap-volume:
  &otlp-mmap-volume
  type: bind
  source: ./export
  target: /otlp/export
services:
  # OpenTelemetry collector actually pull
  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.139.0
    volumes:
      - ./otel-config:/otel-config
    command: ["--config=/otel-config/otel-lgtm-config.yaml"]
    depends_on:
      - lgtm
    ports:
      - "4317"
      - "4318"
      - "8091"

  # The HTTP server with normal java SDK
  java_http_server_sdk:
    image: ghcr.io/jsuereth/mmap-demo:main
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
      HTTP_ENDPOINT_PORT: 8082
      OTEL_SERVICE_NAME: http_java_sdk
      OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION: base2_exponential_bucket_histogram
    # TODO - share definiton w/ mmap collector
    ports:
      - "8082"
    depends_on:
      - otel_collector
  # HTTP server that is instrumented, configured to use SDK MMap
  java_http_server_mmap_sdk:
    image: ghcr.io/jsuereth/mmap-demo:main
    volumes: 
      - ./export:/otlp/export
    environment:
      SDK_MMAP_EXPORTER_FILE: /otlp/export/mmap-throughput.otlp
      HTTP_ENDPOINT_PORT: 8081
      OTEL_SERVICE_NAME: http_java_mmap_sdk
    # TODO - share definiton w/ mmap collector
    ports:
      - "8081"
  # Collector for the MMAP sdk file that will send OTLP to the otel collector.
  mmap_collector:
    image: ghcr.io/jsuereth/mmap-collector:main
    depends_on:
      - otel_collector
      - java_http_server_mmap_sdk
    environment:
      SDK_MMAP_EXPORTER_FILE: /otlp/export/mmap-throughput.otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    # TODO - share definiton w/ demo
    volumes: 
      - ./export:/otlp/export
    restart: unless-stopped
  # Load tester for our HTTP server
  k6_mmap_loadtester:
    image: grafana/k6:latest
    command: ["run", "-o", "experimental-opentelemetry", "/config/k6-load-test.js"]
    environment:
      TARGET_URL: http://java_http_server_mmap_sdk:8081/
      VIRTUAL_USERS: 200
      K6_OTEL_SERVICE_NAME: java_http_mmap_load_test
      K6_OTEL_FLUSH_INTERVAL: 10s
      K6_OTEL_EXPORTER_TYPE: grpc
      K6_OTEL_GRPC_EXPORTER_INSECURE: true
      K6_OTEL_GRPC_EXPORTER_ENDPOINT: lgtm:4317
      K6_OTEL_METRIC_PREFIX: k6_
    depends_on:
      - java_http_server_mmap_sdk
    volumes: 
      - ./k6-config:/config
  k6_sdk_loadtester:
    image: grafana/k6:latest
    command: ["run", "-o", "experimental-opentelemetry", "/config/k6-load-test.js"]
    environment:
      TARGET_URL: http://java_http_server_sdk:8082/
      VIRTUAL_USERS: 200
      K6_OTEL_SERVICE_NAME: java_http_sdk_load_test
      K6_OTEL_FLUSH_INTERVAL: 10s
      K6_OTEL_EXPORTER_TYPE: grpc
      K6_OTEL_GRPC_EXPORTER_INSECURE: true
      K6_OTEL_GRPC_EXPORTER_ENDPOINT: lgtm:4317
      K6_OTEL_METRIC_PREFIX: k6_
    depends_on:
      - java_http_server_sdk
      - lgtm
    volumes: 
      - ./k6-config:/config
  # cAdvisor (Collects container CPU and Memory metrics)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8090:8080"
    privileged: true
    # Ensures cAdvisor gets enough permissions to monitor the host
  lgtm:
    # Use the official all-in-one image
    image: grafana/otel-lgtm:latest
    container_name: lgtm-backend
    ports:
      # Grafana UI
      - "3000:3000" 
      - "4317" 
      - "4318" 
    volumes:
      # Persist the data for Prometheus, Loki, and Tempo across restarts
      - dashboard-data:/data
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    #environment:
      # Optional: Troubleshooting
      # ENABLE_LOGS_ALL: "true" 
    depends_on:
      # Ensure cAdvisor is running before the collector starts scraping it
      - cadvisor 
    restart: unless-stopped
volumes:
  # Database/Dashbaords
  dashboard-data: {}