global:
  scrape_interval: 5s 

scrape_configs:
  # TODO - do we really need our own metrics?
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'otel_collector'
    static_configs:
      - targets: ['otel_collector:8091']